- type: job
  id: Pilot
  name: job-name-pilot
  playTimeTracker: JobPilot
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 14400 # 4h
  startingGear: PilotGear
  icon: "JobIconPilot"
  setPreference: false
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PilotGear
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    id: PilotPDA
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckTieRed
    pocket1: WeaponPistolMk58
