- type: parallax
  id: Blank

- type: parallax
  id: Default #NES14-Changes
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/FrontierParallaxBG.png"
      slowness: 0.9996
      scrolling: "-0.01, 0"
      scale: "1, 1"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/Teneta.png"
      slowness: 0.99
      tiled: false
      scale: "0.6, 0.6"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/AsteroidsSmall.png"
      slowness: 0.95
      scrolling: "0.1, 0"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/AsteroidsMedium.png"
      slowness: 0.88569
      scrolling: "0.3, 0"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/AsteroidsBig.png"
      slowness: 0.7856
      scrolling: "0.5, 0"
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.875
        scrolling: "0.0059, 0"
  layersLQUseHQ: false

# Because hyperspace and the menu need their own.
- type: parallax
  id: FastSpace
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/WarpParallaxBG.png"
      slowness: 0.2
      scale: "3, 3"
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars.toml"
      slowness: 0.0001
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizards_star_slower"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars-2.toml"
      slowness: 0.000001
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_dim"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim.toml"
      slowness: 0.001
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_dim_faster"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim-2.toml"
      slowness: 0.000001
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.5
  layersLQUseHQ: false
