- type: parallax
  id: Blank

- type: parallax
  id: Default #NES14-Changes
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/PurpleParallax2.png"
      slowness: 0.95
      scrolling: "-0.01, 0"
      scale: "1, 1"
    # - texture:
    #     !type:GeneratedParallaxTextureSource
    #     id: "hq_wizard_stars"
    #     configPath: "/Prototypes/Parallaxes/parallax_config_stars.toml"
    #   slowness: 0.93
    #   scrolling: "-0.02, 0"
    # - texture:
    #     !type:GeneratedParallaxTextureSource
    #     id: "hq_wizard_stars_faster"
    #     configPath: "/Prototypes/Parallaxes/parallax_config_stars-2.toml"
    #   slowness: 0.9
    #   scrolling: "-0.03, 0"
    # - texture:
    #     !type:GeneratedParallaxTextureSource
    #     id: "hq_wizard_stars_dim_faster"
    #     configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim-2.toml"
    #   slowness: 0.87
    #   scrolling: "-0.04, 0"
    # - texture:
    #     !type:GeneratedParallaxTextureSource
    #     id: "hq_wizard_stars"
    #     configPath: "/Prototypes/Parallaxes/parallax_config_stars.toml"
    #   slowness: 0.8
    #   scrolling: "-0.05, 0"
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.875
        scrolling: "0.0059, 0"
  layersLQUseHQ: false

# Because hyperspace and the menu need their own.
- type: parallax
  id: FastSpace
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/NES/Parallaxes/WarpParallaxBG.png"
      slowness: 0.2
      scale: "3, 3"
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars.toml"
      slowness: 0.0001
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizards_star_slower"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars-2.toml"
      slowness: 0.000001
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_dim"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim.toml"
      slowness: 0.001
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_dim_faster"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim-2.toml"
      slowness: 0.000001
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.5
  layersLQUseHQ: false
